name: arcane-ascension
version: '1.0-SNAPSHOT'
main: com.github.koloss.ascension.AscensionPlugin
api-version: '1.21'
commands:
  help:
    description: Gives Tome of Ascension
    usage: /help
  skills:
    description: Displays current modifiers
    usage: /skills